### ISSUE TITLE
Better README.md

### ISSUE THREAD

**Issue by rustyxlol** [rustyxlol/Match-Game#6]

**Comment by dylan-power** [comment]
Hi, I'd like to take this issue. Are there any guidelines for what you want to see in the README? Thank you.

**Comment by rustyxlol** [comment]
@dylan-power A minimalist one like the one I have for etch a sketch [here](https://github.com/rustyxlol/etch-a-sketch) would suffice, along with a similar demonstration/video for the updated code(current build)

**Comment by rustyxlol** [comment]
@dylan-power any updates on this?

**Comment by rustyxlol** [comment]
Closing.
